Repository easternenterprise/Decor, pull requests merged in 2021-08, with the labels that each got.

#1 feat(chore): Initial Project Setup
  .github/workflows/build.yml
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  gradle.properties
  src/main/kotlin/com/github/eebhushan/githubtheme/MyBundle.kt
  src/main/kotlin/com/github/eebhushan/githubtheme/listeners/MyProjectManagerListener.kt
  src/main/kotlin/com/github/eebhushan/githubtheme/services/MyApplicationService.kt
  src/main/kotlin/com/github/eebhushan/githubtheme/services/MyProjectService.kt
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#2 feat(chore): pull request template added
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#6 fix(workflow): Verify build failed due to lower version of Java and dependencies is fixed
  .github/workflows/build.yml
  .github/workflows/release.yml
  CHANGELOG.md
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#7 created dark, light and gray theme
  CHANGELOG.md
  gradle.properties
  src/main/kotlin/com/easternenterprise/jetbraintheme/MyBundle.kt
  src/main/kotlin/com/github/eebhushan/githubtheme/listeners/MyProjectManagerListener.kt
  src/main/kotlin/com/github/eebhushan/githubtheme/services/MyApplicationService.kt
  src/main/kotlin/com/github/eebhushan/githubtheme/services/MyProjectService.kt
  src/main/resources/Jetbrain_Dark.theme.json
  src/main/resources/Jetbrain_Dark.xml
  src/main/resources/Jetbrain_Gray.theme.json
  src/main/resources/Jetbrain_Gray.xml
  src/main/resources/Jetbrain_Light.theme.json
  src/main/resources/Jetbrain_Light.xml
  src/main/resources/META-INF/plugin.xml
Labels: enhancement
